name: master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-node@v4"
      with:
        node-version: '18'
    - name: "Build"
      shell: pwsh
      run: |
        pwsh build.ps1
    # バージョン取得
    - uses: "repy-actions/chrome-extensions-version@master"
      id: "check_version"
      with:
        manifest-path: 'src/manifest.json'
    # 同じバージョンのリリースがあるかチェック
    - uses: "actions/github-script@v2"
      id: "check_release"
      continue-on-error: true
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        script: |
          github.repos.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: "v${{ steps.check_version.outputs.version }}",
          });
    - name: "Create Release"
      if: "steps.check_release.outcome == 'failure'" # 同じバージョンのリリースがないとき実行
      id: "create_release"
      uses: "actions/create-release@v1"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        tag_name: "v${{ steps.check_version.outputs.version }}"
        release_name: "Version ${{ steps.check_version.outputs.version }}"
        body: ""
        draft: false
        prerelease: false
    - name: "Release Zip"
      if: "steps.check_release.outcome == 'failure'" # 同じバージョンのリリースがないとき実行
      uses: "actions/upload-release-asset@v1"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        upload_url: "${{ steps.create_release.outputs.upload_url }}"
        asset_path: "./YTAdBlock.zip"
        asset_name: "YTAdBlock.zip"
        asset_content_type: "application/zip"
